### ISSUE TITLE
Image Orientation

### ISSUE THREAD

**Issue by dcworldwide** [gre/gl-react-image#1]
I've noticed that this library handles image orientation differently to the standard RN Image component. Perhaps we need to borrow the exif logic from the later. 

Tested on Android Simulator. 

![screenshot_20160625-170729](https://cloud.githubusercontent.com/assets/4898751/16355359/9d76725a-3af7-11e6-808e-2c7d7b478fa1.png)

<img width="324" alt="screen shot 2016-06-25 at 17 16 21" src="https://cloud.githubusercontent.com/assets/4898751/16355407/09dd4bd4-3af9-11e6-854c-3630c58bade4.png">

**Comment by gre** [comment]
I guess it's more à bug in gl-react-native then.
What is weird is we use the RCTImage loader. Part of the code of
RCTImageView.

Need to see if RCTImageView do something more to solve this.

Le sam. 25 juin 2016 09:10, Danijel Cole <notifications@github.com> a
écrit :

**Comment by dcworldwide** [comment]
Hmm yeah thats odd then, I've uploaded the exif info if that helps. I'm still wrapping my head around the intricacies of exif...

**Comment by gre** [comment]
going to investigate a bit. BTW found this nice test collection: https://github.com/recurser/exif-orientation-examples

**Comment by gre** [comment]
I've written a test in the example app of gl-react-native.

It does not look like the bug exists on iOS:

<img width="487" alt="screen shot 2016-07-02 at 12 01 15" src="https://cloud.githubusercontent.com/assets/211411/16539761/d1d633dc-404c-11e6-8250-5fd9bcbc6043.png">

However on Android:

<img width="432" alt="screen shot 2016-07-02 at 12 06 15" src="https://cloud.githubusercontent.com/assets/211411/16539777/64e83616-404d-11e6-9214-fbd5b6c54624.png">


I'm going to fix the Android implementation

**Comment by dcworldwide** [comment]
Neat. That's really useful 👍

**Comment by dcworldwide** [comment]
@gre will try to test Monday

**Comment by logileifs** [comment]
Was this resolved? Just tried on Samsung S5, RN 0.44 and GLImage still did not respect the EXIF rotation info
