### ISSUE TITLE
Large base64 images don't load into component.

### ISSUE THREAD

**Issue by ChristianTucker** [gre/gl-react-image#10]
This is the only information presented:

```
[PERF ASSETS] Loading image at size {4288, 2848}, which is larger than the screen size {750, 1334}
```

Device is iPhone running iOS 10.2

Below is a screenshot of the image not loading (The GLImage is inside the white border) the blurred background is of the image supplied, which shows that the image is valid.

![](https://cdn.discordapp.com/attachments/271475009443201035/286236861796712449/image.png)

**Comment by gre** [comment]
I think it's not just related to base64 but any images. I think there is a technical limitation in OpenGL of the texture size and if you overflow it, it's likely to render nothing.

What iPhone device is it?
according to http://answers.unity3d.com/questions/563094/mobile-max-texture-size.html
limits would be (for OpenGL ES 2.0)

**Max 2048x2048**
iPhone 3GS
iPhone 4
iPad
**Max 4096x4096**
iPhone 4S
iPhone 5
iPad 2
iPad 3

I'm pretty sure iPhone 6/7 still are on that same 4096px limit and 4288 overflow that
