### ISSUE TITLE
GLImage inside SurfaceView is not visible on android

### ISSUE THREAD

**Issue by gevorg94** [gre/gl-react-image#11]
it shows black view

**Comment by mayaa6** [comment]
@gevorg94 save problem

**Comment by mayaa6** [comment]
@gevorg94 Since this issue is closed, have you got the solution?

**Comment by gre** [comment]
"it's just black" is the "undefined is not a function" of WebGL,

really needs more information, like maybe show an example?

it's likely your problem isn't related to gl-react-image but to gl-react. maybe using an invalid format for the image? or maybe it's an actual bug? but please provide a reproducible minimal example. thx

**Comment by mayaa6** [comment]
@gre This simple demo show image in iOS, but show black in android device. No error is alerted.

```javascript
import React, {Component} from "react";
import {Image, View} from "react-native";
import {Surface} from "gl-react-native";
const {Image: GLImage} = require("gl-react-image");
import ImageEffects from './ImageEffects';

export default class Example extends Component {
  render () {
    return (
      <Surface width={300} height={300} ref="surface">
        <ImageEffects saturation={1}>
          <GLImage
            source="https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png"
            resizeMode="cover"
            imageSize={{width: 300, height: 300}}
          />
        </ImageEffects>
      </Surface>
    );
  }
}
```

**Comment by gre** [comment]
so this code is for gl-react v2 and using an older gl-react-image I guess?

can you tell me the specific versions

```
npm ls gl-react gl-react-native gl-react-image
```

**Comment by mayaa6** [comment]
@gre is this true?
```
├── gl-react@2.2.10
├── gl-react-image@0.0.2
├── gl-react-native@2.47.0
```

**Comment by linwenchao** [comment]
same here, any solutions?

`<Surface width={40} height={40}>
    <GLImage source={this.state.selectedPhotos[0]} resizeMode="cover" />
</Surface>`

`
gl-react@v2
gl-react-image@v0.1
gl-react-native@v2
`
