### ISSUE TITLE
GLImage error on import

### ISSUE THREAD

**Issue by nahuelburgos** [gre/gl-react-image#12]
I'm building a react native application and I'm getting this error when importing GLImage:

**ExceptionsManager.js:71 Unhandled JS Exception: (0 , _glReact.GLSL) is not a function**

The error is on line 37 of lib/index.js:

**vert: (0, _glReact.GLSL)(_templateObject),**

These are my dependencies:
    "gl-react": "^2.2.10",
    "gl-react-image": "^3.1.0",
    "gl-react-native": "^2.47.0",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",

**Comment by gre** [comment]
gl-react-image@3 is for gl-react@3
For gl-react@2, please stay on gl-react-image@2
