### ISSUE TITLE
Cant set resizeMode=free

### ISSUE THREAD

**Issue by anoopmm** [gre/gl-react-image#15]
Cant set resizeMode={'free'}
  ##![screenshot_20171208-100945](https://user-images.githubusercontent.com/16194055/33751339-468b8678-dc00-11e7-839e-4ed5e7617494.png)

As said here
#9

**Comment by gre** [comment]
This feature is only available from gl-react-image 3.1.0 which needs gl-react v3 and according to your error I believe you are still using gl-react v2?

If you want this feature but still using gl-react v2 you can still fork this lib and backport it ;)

**Comment by anoopmm** [comment]
Yes, I am still using V2 :).Thanks
