### ISSUE TITLE
children

### ISSUE THREAD

**Issue by stoffern** [gre/gl-react-image#2]
GLImage is not taking {children} into account.

These examples will not work.
```html
<Surface>
  <GLImage />
  <GLImage />
</Surface>

```
```html
<Surface>
  <GLImage>
    <Text>Test</Text>
  </GLImage>
</Surface>
```

**Comment by gre** [comment]
```html
<Surface>
  <GLImage />
  <GLImage />
</Surface>
```

Surface currently supports only one children. It's the root of the graph tree. Not sure what you want to do with this usecase, but what about:

```html
<Surface>
  <GLImage />
<Surface>
</Surface>
  <GLImage />
</Surface>
```

---

```html
<Surface>
  <GLImage>
    <Text>Test</Text>
  </GLImage>
</Surface>
```

What is this supposed to do?!

GLImage is for rendering an image. it doesn't support children.

**Comment by stoffern** [comment]
@gre sorry, this is the wrong place to put this issue! :disappointed: 
i was trying to place a image over another image inside the Surface.
Ref here with text: https://projectseptemberinc.gitbooks.io/gl-react/content/docs/examples/3.html

**Comment by stoffern** [comment]
@gre closing this issue, i missunderstood it all :smile:

**Comment by gre** [comment]
technically you could have many images / contents in a shader, if you have multiple uniforms.
like used in here : http://greweb.me/2016/07/projectseptember-opengl/

**Comment by stoffern** [comment]
Funny, i was just looking at it! :+1:

**Comment by stoffern** [comment]
@gre is it possible to set different sizes on the images in a smart way?
or will this have to be done in the shader?

  ```html
<GL.Node shader={shaders.GLSticker}>
    <GL.Uniform name="image">
      <GLImage
        source={image}
        imageSize={{ width: 300, height: 300 }}
        resizeMode="cover"
      />
    </GL.Uniform>
    <GL.Uniform name="overlay">
      <GLImage
        source={overlay}
        imageSize={{ width: 20, height: 20 }}
        style={{ width: 20, height: 20, position: 'absolute', top: 0, left: 0}}
        resizeMode="contain"
      />
    </GL.Uniform>
  </GL.Node>

```

**Comment by gre** [comment]
`GLImage` don't have such *style* parameter. It's not like an "usual" React Native component.
However, there is a `width` and `height` props, that allows to scale down the size of a framebuffer.
Not sure if this is what you are looking for, but it's possible with GLImage.

Otherwise, if it's about doing layout, you will have to do it in the shader itself. (you are sure you need to do the 2 images in a same shader?)

**Comment by stoffern** [comment]
I am trying to create one Surface with:
```
- a background image
- one sticker png image placed in top left side over the background.
```

**Comment by gre** [comment]
if that sticker png image have to be in the Surface, yeah, the only way is via a shader

**Comment by gre** [comment]
if you don't need to have that image in the shader, it could just be a element placed on top of the Surface.
