### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by songxiaoliang** [gre/gl-react-image#20]
com.facebook.react.common.JavascriptException: gl-shader: Error compiling shader:

ERROR: 0:6: 'res' : Only consts can be used in a global initializer 
ERROR: 0:6: 'res' : Only consts can be used in a global initializer 
ERROR: 2 compilation errors.  No code generated.

**Comment by songxiaoliang** [comment]
@gre 
"gl-react": "^3.13.0",
"gl-react-image": "^3.1.0",
"gl-react-native": "^3.13.0",

**Comment by songxiaoliang** [comment]
<Surface style={styles.surfaceItem}>
  <Sierra {...this.props}>
    <GLImage source=  {{uri: imagePath}} resizeMode='cover' />
  </Sierra>
</Surface>

**Comment by songxiaoliang** [comment]
@gre 
  <Surface style={styles.surfaceItem}>
      <Sierra {...this.props}>
          <GLImage source={{uri: imagePath}} resizeMode='cover' />
      </Sierra>
  </Surface>

**Comment by songxiaoliang** [comment]
@gre 

            <Surface style={styles.surfaceItem}>
              <Sierra {...this.props}>
                <GLImage source={{uri: imagePath}} resizeMode='cover' />
              </Sierra>
            </Surface>

**Comment by gre** [comment]
was reported originally here https://github.com/gre/gl-react/issues/163 going to fix it now

**Comment by songxiaoliang** [comment]
perfect

**Comment by farazirfan47** [comment]
Did this fixed?
