### ISSUE TITLE
Rotation of image

### ISSUE THREAD

**Issue by loic-lopez** [gre/gl-react-image#22]
Hi,

How i can apply a rotation to my picture bellow the dimensions : 

```
Object {
13:06:33 [exp]   "height": 3264,
13:06:33 [exp]   "uri": "file:///var/mobile/Containers/Data/Application/8196F3EA-3555-476F-B70F-E76CBBFBB3F8/Library/Caches/ExponentExperienceData/%2540devlyl%252Flyl/Camera/5FA1D6E2-D99E-4675-AF6E-CB96A2367015.jpg",
13:06:33 [exp]   "width": 1836,
13:06:33 [exp] }
```
Result of taken picture by the camera: 
![img_0111](https://user-images.githubusercontent.com/17724398/40611918-9528a3ca-6278-11e8-814a-b8d54bdbbc93.png)

Displayed with GLImage:
![img_0113](https://user-images.githubusercontent.com/17724398/40611952-b5f3d28c-6278-11e8-9f78-d8f9ec7a92d1.png)

Thanks for reply

**Comment by loic-lopez** [comment]
Up please

**Comment by brysonandrew** [comment]
@loic-lopez I had an issue similar to this and I fixed it by resizing the image before passing it as a uniform. Although I was using just the standard Node from "gl-react" not "gl-react-image"

3264 x 1836 is pretty big so I assume this is your issue also. Try halving this.

Can be done on expo with https://docs.expo.io/versions/latest/sdk/imagemanipulator/

**Comment by fdagostino** [comment]
Up please!

**Comment by gre** [comment]
I believe @brysonandrew answer's is correct here. You can use any React Native utility to do the resizing but to me it's not in the scope of this library.
