### ISSUE TITLE
Could projective interpolation be done using GLSL?

### ISSUE THREAD

**Issue by paluh** [gre/gl-react-image#23]
Hi,

Thanks for all your really cool work on this and other libraries/tools!

I'm just starting to play with `GLSL` and I wonder if projective interpolation (something like https://bl.ocks.org/mbostock/10571478) could be done (without insane amount of work) as shader?
I know that perspective operations are handled in OpenGL/WebGl in another layer, but I'm curious if such an image transformation could be part of this library which is based on fragment shaders.

@gre What do you think?

**Comment by gre** [comment]
sorry for late response.
probably not with this library, but it's possible to implement in GLSL i think.
