### ISSUE TITLE
Zoom and Crop value translation

### ISSUE THREAD

**Issue by AfflatusX** [gre/gl-react-image#25]
Hi @gre  thanks for the awesome library!

I am trying to use gl-image with crop (center) and zoom, but I am not sure how the prop values translates to the traditional x,y and zoom % value.

For example, given an image, which I know I need to zoom it to 50% of original size and then crop from {x: 10, y: 20} with size {width: 100, height:200}, how would I achieve that using zoom and center properties on the gl-react-image?

Would really appreciate if you can share some thoughts on this!

**Comment by gre** [comment]
the library abstracted out this with zoom/crop so it's agnostic to the image size / canvas resolution.

but that's a good point the usecase is legit. I'll try to see what we could have to satisfy this.

**Comment by gre** [comment]
if you are able to set x,y,w,h we could offer a way but that would let you free and the lib would not preserve the image ratio.

regarding how to use zoom and center, you might want to check out the example: https://gl-react-image.surge.sh/#resizeMode="cover" if you click on zoom and center, you get the basic idea of what the prop are doing.

**Comment by AfflatusX** [comment]
thanks for the reply! 

Before going too deep into the details, I want to clarify one thing with regarding to memory usage:

given image of size 500 * 400 px;

Scenario 1: a surface of size 500 * 400,  not setting zoom/center props
Scenario 2: a surface of size 250 * 200, but zoom to 2x

Do they use same amount of memory? or the second one will use less?

**Comment by AfflatusX** [comment]
> if you are able to set x,y,w,h we could offer a way but that would let you free and the lib would not preserve the image ratio.

That's fine, I can make sure w, h preserves image ratio. However, I would still need a way to apply the crop based on a certain zoom (for example, 150%)

So right now I have an component that allows user to drag around and zoom the image, which yields a zoom value (percentage, 2x zoom -> 200%) and a coordinate value (x,y) with regard to the offset where the crop should happens at.

I took a look at the example above, and I know how the number affects the zoom level - however I can't translate the percentage value I have (50%) to the zoom value in Surface (between 0 - 1)
