### ISSUE TITLE
Can I use standard <Image/> to load an image into the Surface?

### ISSUE THREAD

**Issue by Orxcle-xx** [gre/gl-react-image#26]
Hi,

Can I use standard <Image/> to load an image into the Surface?
Tried it, doesn't work. Maybe I am doing something wrong. Is it supported?
```
<Surface ...> 
<Image src={....}/>
</Surface>
```

Thank you.

**Comment by gre** [comment]
`src` is named `source` in this library.
This is to make a clear distinction on the fact it is NOT like an `<img` . It's for gl-react and it depends on the implementation (on gl-react-dom it's a string even tho actually it could be literally anything, like a node itself, but on gl-react-native it's not a string, it's using the same React Native source's format)
