### ISSUE TITLE
This doesn't work with gl-react-expo

### ISSUE THREAD

**Issue by Uniphix** [gre/gl-react-image#27]
React Native with Expo/ExpoKit
Expo: 32.0.0
ExpoKit: 32.0.7
React Native: SDK 32 / 0.59.1
gl-react: 3.15.0
gl-react-expo: 3.16.3
gl-react-image: 3.1.1

I am using the latest gl-react, gl-react-expo and it does not work with gl-react-image.  I get no rendering what so ever.  If I use the example of the "HelloBlue" it renders fine.

I also get a warning about createAsyncObject too.  

I am also using Expo 32 and React 0.59 SDK

**Comment by Uniphix** [comment]
To be exact the error I get is:

webgltexture-loader-expo: ExponentGLObjectManager.createObjectAsync is not available. Make sure to use the correct version of Expo

**Comment by afrozopsy** [comment]
@gre Hey!! Can you look it into it please, I m having the same problem. It renders nothing on the surface and posts a warning that says Node#1 uniform t: no loader found for value "Url we give it."

**Comment by afrozopsy** [comment]
@Uniphix Hello, have you got a workaround about it?

**Comment by gre** [comment]
Can you confirm this is now fixed in this upcoming version? Thanks

```
 - gl-react-dom => 5.2.2-next.6+d39872d
 - gl-react-expo => 5.2.2-next.6+d39872d
 - gl-react-headless => 5.2.2-next.6+d39872d
 - gl-react-native => 5.2.2-next.6+d39872d
 - gl-react => 5.2.2-next.6+d39872d
```
