### ISSUE TITLE
add a video as source in GlImage 

### ISSUE THREAD

**Issue by lilyBrainy** [gre/gl-react-image#30]
how can I add a video as source in GlImage ? 
because in the read me section it says that in gl-react-image anything can be the source, it can be a video, a canvas..

**Comment by gre** [comment]
yeah it's independent from this libary, gl-react-image is just a shader, the texture can be anything. it's up to the gl-react side to support video basically (and it already works in web)

some examples in https://gl-react-cookbook.surge.sh/blurvideo

**Comment by lilyBrainy** [comment]
can I implement this on expo ?
