### ISSUE TITLE
overlaying two images

### ISSUE THREAD

**Issue by andyfen** [gre/gl-react-image#4]
firstly thanks for fantastic work.

is there any way to overly two images and put a background image behind an main image?

i had a couple of bashes but couldn't really get anything working, would it need to be done with shaders ?

i'm not too worried about about rotating it but to create something like this

![](https://dannypallett.files.wordpress.com/2011/03/polarbearoids_0002.jpg)

**Comment by madebysquares** [comment]
@andyfen did you ever find a way to acheive this effect? Trying to do something similar.

**Comment by thequicksort** [comment]
This is a really good question and I haven't been able to find a way to do it yet.

**Comment by gre** [comment]
can you explain a bit more what the effect is about, do you have a showcase somewhere? 
Is it just about putting the image on top of that 'old photo style' background or is there more effects on top of the image itself involved?

BTW, it's probably off topic of this library, and should be another library / shader.

Thanks

**Comment by gre** [comment]
i'm sorry but this is out of scope of this lib so i'm going to close this. this can definitely be implemented in a custom shader tho
