### ISSUE TITLE
Apply rotation to an image

### ISSUE THREAD

**Issue by sscaff1** [gre/gl-react-image#5]
Is there a way to apply rotation to an image? I can wrap it in a surface, but if I want to captureFrame of that surface it's not rotated. Anything else I can use to rotate the image?

**Comment by gre** [comment]
I guess you could define a component that implement rotation in a shader?
I had hard time to think if this shouldn't be in gl-react-image, but that would be a bit tricky to implement with the resizeMode mecanism I guess.

**Comment by gre** [comment]
```js
<GLRotate rotate={45}>
  <GLImage ... />
</GLRotate>
```

or 

```js
<GLImage source={<GLRotate ... />} ... />
```

I guess GLRotate implementation might also need the size if you want it preserve image ratio, mmh

**Comment by sscaff1** [comment]
@gre I was thinking along your original thoughts. I don't think this should be part of GLImage - more wanted a shader code so that I could apply the rotation to a child. I just don't know enough openGL to implement a shader.

**Comment by gre** [comment]
rotation should be straightforward to implement except the hard part is how to implement the rotation center/scale & also preserve the ratio.
also when you say rotation, are you looking to support any angle or just 0, 90, 180, 270 deg ?

**Comment by sscaff1** [comment]
For the time being, I'm good with 0, 90, 180, and 270

**Comment by sscaff1** [comment]
Any help on this is greatly appreciated.

**Comment by gre** [comment]
Hi @sscaff1 ,

I recently worked on a rotation shader that apply a centered rotation (with an angle) & scale on a texture. It only supports square images. but you can workaround it by inverting width & height of the Surface for 90° and 270° cases.

```glsl
precision highp float;

varying vec2 uv;
uniform float angle;
uniform float scale;
uniform sampler2D t;

void main () {
  mat2 rotation = mat2(
    cos(angle), -sin(angle),
    sin(angle),  cos(angle)
  );
  vec2 p = (uv - vec2(0.5)) * rotation / scale + vec2(0.5);
  if (p.x < 0.0 || p.x > 1.0 || p.y < 0.0 || p.y > 1.0)
    gl_FragColor = vec4(0.0);
  else
    gl_FragColor = texture2D(t, p);
}
```

**Comment by sscaff1** [comment]
You are awesome @gre 

I modified the code above slightly but for some reason it's not rendering anything. I'm not getting any errors. Any ideas? I just assume my scale is 1.

```
// my shader
import React, { PropTypes } from 'react';
import GL from 'gl-react';

const shaders = GL.Shaders.create({
  rotate: {
    frag: `
    precision highp float;

    varying vec2 uv;
    uniform float angle;
    uniform float width;
    uniform float height;
    uniform sampler2D t;

    void main () {
    mat2 rotation = mat2(
      cos(angle), -sin(angle),
      sin(angle),  cos(angle)
    );
    vec2 p = (uv - vec2(width / height)) * rotation + vec2(width / height);
    if (p.x < 0.0 || p.x > 1.0 || p.y < 0.0 || p.y > 1.0)
      gl_FragColor = vec4(0.0);
    else
      gl_FragColor = texture2D(t, p);
    }`
  }
});

export default GL.createComponent(
  ({ children: t, angle, height, width }) => (
    <GL.Node
      shader={shaders.rotate}
      uniforms={{
        t,
        angle,
        height,
        width,
      }}
    />
  ),
  {
    displayName: 'Rotation',
    propTypes: {
      children: PropTypes.any.isRequired,
      angle: PropTypes.string.isRequired,
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    }
  }
);
```
in my render function:
```
<Rotation height={image.size.height} width={image.size.width} angle={image.imageFilters.rotate}>
  {image.uri}
</Rotation>

**Comment by gre** [comment]
`vec2(width / height)` looks wrong.
I'm not sure what you try to achieve but `vec2(0.5, 0.5)` is the center of your image, whatever the width,height (because uv move from 0 to 1 for x and y)

**Comment by gre** [comment]
jsfiddle

https://jsfiddle.net/greweb/vLdnrgm7/

**Comment by sscaff1** [comment]
Thank you so much for your help!
