### ISSUE TITLE
how to load local image?

### ISSUE THREAD

**Issue by XHTeng** [gre/gl-react-image#6]
I try to load in this way,but it not work
![snip20160919_11](https://cloud.githubusercontent.com/assets/17663111/18627968/8e8f8916-7e90-11e6-83a1-b743d138219f.png)

**Comment by gre** [comment]
This doesn't work ([yet](https://github.com/ProjectSeptemberInc/gl-react-native/issues/100)),
see https://github.com/ProjectSeptemberInc/gl-react-native/issues/66#issuecomment-227383199

and actually now, resolveAssetSource is exported out of gl-react-native:

```js
import {Surface, resolveAssetSource} from "gl-react-native";

...

<GLImage source={resolveAssetSource("./logo.jpg")} ... />
```

**Comment by XHTeng** [comment]
thanks ！

**Comment by leoabacade** [comment]
Hello gre,

I am trying to display an image from uri below

content://media/external/images/media/58367

which is a file location at device

and 
<Image source={{ uri: "content://media/external/images/media/58367" }} style={styles.GL_displaied}/>
is working properly

but 
<GLImage source={resolveAssetSource("content://media/external/images/media/58367")} ... />
is not working

do you have any suggestions?

**Comment by gre** [comment]
resolveAssetSource only works with local image, not with this content://, have you tried doing:

```
<GLImage source={{ uri: "content://media/external/images/media/58367" }} ... />
```

?

**Comment by leoabacade** [comment]
yes I did, the image is not rendered with
`<GLImage source={{ uri: "content://media/external/images/media/58367" }} ... />`
that's why I am pretty confused

**Comment by gre** [comment]
mmh.
Actually I think it's because Android uri format in `gl-react-native` is more limited, it doesn't accept all format of `<Image source>` i'm afraid. Also there is no public API for "parsing" the ImageSource in the RN Java.
maybe I did missed when importing RN logic here https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/GLImage.java#L89

**Comment by themakerman** [comment]
@leoabacade did it worked for you ? loading image with content?
