### ISSUE TITLE
Cannot use it inside AnimatedSurface

### ISSUE THREAD

**Issue by desmondhume** [gre/gl-react-image#7]
The component complains about the value of `width` when it's rendered inside an AnimatedSurface. Am I doing something wrong or is it not supported?

**Comment by gre** [comment]
Do you have a code sample to show? I'm not sure to understand.
Thanks

**Comment by desmondhume** [comment]
```jsx
<AnimatedSurface
  width={width}
  height={400}>
  <GLImage
    source={this.props.currentCapture}
    style={{ width: this.state.captureWidth, height: this.state.captureHeight }}
    resizeMode="cover"
  />
</AnimatedSurface>
```

`width` is an instance of `Animated.Value`

This is the error i get:

![screen shot 2016-09-28 at 12 40 04](https://cloud.githubusercontent.com/assets/1183744/18910524/b85d53ce-8578-11e6-8c67-8f644fdf8113.png)

**Comment by desmondhume** [comment]
Ok sorry, I fixed this by adding `width` and `height` props to the `GLImage` tag.

**Comment by gre** [comment]
yeah, gl-react-image does not support animated value as it needs to do some calculation.. that would be interesting to have this supported though, but i'm not exactly sure how to implement this. Animated don't have a public standard api for mapping a value ( https://github.com/animatedjs/animated/issues/41 )

**Comment by gre** [comment]
mmh, actually yeah, width and height provided to GLImage have to be the image size, not the actually surface size, so maybe things works? mmh
