### ISSUE TITLE
Zooming out?

### ISSUE THREAD

**Issue by ChristianTucker** [gre/gl-react-image#9]
I know you can zoom to the images original size (1) but is it possible to zoom out?? Setting the zoom to over 1 does nothing.

**Comment by gre** [comment]
the zoom/center is currently only used when `resizeMode="cover"`, to define the center of gravity. `"cover"` mode makes sure the image never goes out of bound ( https://github.com/gre/gl-react-image/blob/6c86d647eb3ae1cf977a4701e8777ae258fc44a0/src/Image.js#L52 ensure that), that means a zoom > 1 would always be like zoom=1, at least in that resizeMode.

Maybe we can introduce a new `"free"` resizeMode (free might be a good name actually!) for what you are asking, that don't clamp the cropping rectangle to the viewport. I think the implementation would be very similar to the one of the `case "cover"` but without the `rectClamp` line of code I mentioned.

Would you like to provide a PR?

**Comment by gre** [comment]
@ChristianTucker fixed by 3.1.0

**Comment by gre** [comment]
e.g https://gl-react-image.surge.sh/#resizeMode=%22free%22&zoom=4
